export const FETCH_GROCERY_ITEMS_SUCCESS = 'FETCH_GROCERY_ITEMS_SUCCESS';
export const FETCH_GROCERY_ITEMS_FAILURE = 'FETCH_GROCERY_ITEMS_FAILURE';
export const ADD_GROCERY_ITEM_SUCCESS = 'ADD_GROCERY_ITEM_SUCCESS';
export const ADD_GROCERY_ITEM_FAILURE = 'ADD_GROCERY_ITEM_FAILURE';
export const DELETE_GROCERY_ITEM_SUCCESS = 'DELETE_GROCERY_ITEM_SUCCESS';
export const BUY_GROCERY_ITEM_SUCCESS = 'BUY_GROCERY_ITEM_SUCCESS';
export const RETURN_GROCERY_ITEM_SUCCESS = 'RETURN_GROCERY_ITEM_SUCCESS';
