export const FETCH_GROCERY_ITEMS_SUCCESS = 'FETCH_GROCERY_ITEMS_SUCCESS';
export const FETCH_GROCERY_ITEMS_FAILURE = 'FETCH_GROCERY_ITEMS_FAILURE';
export const ADD_GROCERY_ITEM_SUCCESS = 'ADD_GROCERY_ITEM_SUCCESS';
export const ADD_GROCERY_ITEM_FAILURE = 'ADD_GROCERY_ITEM_FAILURE';
export const DELETE_GROCERY_ITEM_SUCCESS = 'DELETE_GROCERY_ITEM_SUCCESS';
export const DELETE_GROCERY_ITEM_FAILURE = 'DELETE_GROCERY_ITEM_FAILURE';
export const UPDATE_GROCERY_ITEM_SUCCESS = 'UPDATE_GROCERY_ITEM_SUCCESS';
export const UPDATE_GROCERY_ITEM_FAILURE = 'UPDATE_GROCERY_ITEM_FAILURE';
